prefix =	/usr/local
share =		$(prefix)/share
bindir =	$(prefix)/bin
mandir =	$(share)/man
man1dir =	$(mandir)/man1
pkgname =	autopkgtest
docdir =	$(share)/doc/$(pkgname)
examplesdir =	$(share)/doc/$(pkgname)/examples
sharedir = 	$(share)/$(pkgname)
pythondir = 	$(share)/$(pkgname)/python
sharedir_lnfrom = $(share)/$(pkgname)
etcdir =	/etc
etcconfdir =	$(etcdir)/autopkgtest
etcinitddir =	$(etcdir)/init.d
xenscripts =	$(etcdir)/xen/scripts
cfg_suffix =	.dist

INSTALL =		install
INSTALL_DIRS =		$(INSTALL) -d
INSTALL_PROGRAM =	$(INSTALL) -m 0755
INSTALL_DATA =		$(INSTALL) -m 0644
INSTALL_DOC =		$(INSTALL) -m 0644
