#!/bin/bash -e
#============================================================================
# /etc/xen/vif-route
#
# Script for configuring a vif in routed mode.
# The hotplugging system will call this script if it is specified either in
# the device configuration given to Xend, or the default Xend configuration
# in /etc/xen/xend-config.sxp.  If the script is specified in neither of those
# places, then vif-bridge is the default.
#
# Usage:
# vif-route (add|remove|online|offline)
#
# Environment vars:
# vif         vif interface name (required).
# XENBUS_PATH path to this device's details in the XenStore (required).
#
# Read from the store:
# ip      list of IP networks for the vif, space-separated (default given in
#         this script).
#============================================================================

exec 2>>/var/log/xen-hotplug.log
set -x
case $0 in */*) dir=${0%/*};; *) dir=.;; esac
. "$dir/vif-common.sh"

main_ip=$(dom0_ip)

case "$command" in
    online)
        ifconfig ${vif} ${main_ip} netmask 255.255.255.255 \
		broadcast ${main_ip} up
	ip -f inet6 addr delete dev ${vif} local fe80::fcff:ffff:feff:ffff/64
	ip -f inet neigh add \
	    to 172.18.45.66 \
	    dev ${vif} \
	    lladdr 00:16:3e:7c:aa:7f \
	    nud permanent
	arp -i ${vif} -s 172.18.45.66 00:16:3e:7c:aa:7f pub
        ipcmd='a'
	iptcmd='-A'
        ;;
    offline)
        ifdown ${vif}
        ipcmd='d'
	iptcmd='-D'
        ;;
esac

iptables "$iptcmd" INPUT -i "$vif" -j AdtXenIn
iptables "$iptcmd" FORWARD -i "$vif" -j AdtXenFwd

if [ "${ip}" ] ; then
    # If we've been given a list of IP addresses, then add routes from dom0 to
    # the guest using those addresses.
    for addr in ${ip} ; do
      ip r ${ipcmd} ${addr} dev ${vif} src ${main_ip}
    done 
fi

#S log debug "Successful vif-route $command for $vif."
if [ "$command" == "online" ]
then
  success
fi
