#!/bin/bash
set -e
. ${ADT_XENLVM_SHARE:=/usr/share/autopkgtest/xenlvm}/readconfig

mkdir -p $adt_play $snap

try () { "$@" >/dev/null 2>&1 ||:; }

try xm destroy $adt_xmname
try umount $adt_lvm_baselv
try dmsetup remove $adt_devmapper_cowdev
rm -f $lvfsptr
