#!/bin/bash
set -e

adt_readconfig_needlock=y
. ${ADT_XENLVM_SHARE:=/usr/share/autopkgtest/xenlvm}/readconfig
test $nonoptargs = 0 || fail "non-option arguments not allowed"
rm -f $adt_play/good

$ADT_XENLVM_SHARE/cleanup
xl lvchange -a n $lvm_baselv_namepath ||:
xl lvchange -a n $lvm_cowdata_namepath ||:
xl lvremove $lvm_baselv_namepath ||:
xl lvremove $lvm_cowdata_namepath ||:

rm -rf -- "${adt_play}"
