#!/bin/bash
set -e
fail () { printf >&2 "%s: %s\n" "$0" "$*"; exit 127; }

. /etc/lsb-release

d="${USERV_U_distro-$DISTRIB_CODENAME}"
n="${USERV_U_nominum-adt}"

case "$dn" in
*/*|.*|*.*|*_*_*)	fail 'dangerous format in distro or nominum'	;;
adt*)	;;
*)	fail 'userv adtxenlvm only supports nominums starting with adt' ;;
esac

test -d /var/lib/autopkgtest/xenlvm/"$dn" || fail 'unknown distro or nominum'

run () {
	base="$1"; shift
	exec "$base" --adt-distro="$d" --adt-nominum="$n" "$@"
}

case "$1" in
with)	run adt-xenlvm-with-testbed sh -c 'echo y && exec cat' ;;
pon0)	run adt-xenlvm-on-testbed -- --print0-command ;;
*)	fail 'unknown mode'
esac
