#!/bin/sh
set -e
testdir="$(dirname $(readlink -f $0))"
rootdir="$(dirname $testdir)"

pep8 $rootdir/lib/*.py $rootdir/tools/adt-buildvm-ubuntu-cloud

for v in chroot null schroot lxc qemu; do
    pep8 --ignore E501 $rootdir/virt-subproc/adt-virt-$v
done

pep8 --ignore E501 $rootdir/runner/adt-run $testdir/adt-run $testdir/testdesc
