#!/bin/sh

# This testsuite is part of autopkgtest
# autopkgtest is a tool for testing Debian binary packages
#
# autopkgtest is Copyright (C) 2006-2013 Canonical Ltd.
# Author: Martin Pitt <martin.pitt@ubuntu.com>

set -e
testdir="$(dirname $(readlink -f $0))"
rootdir="$(dirname $testdir)"

if type pyflakes3 >/dev/null 2>&1; then
    FLAKES3=pyflakes3
else
    FLAKES3=pyflakes
fi

pyflakes $rootdir/lib $rootdir/runner/adt-run
$FLAKES3 $testdir/adt-run

for v in chroot null schroot xenlvm; do
    pyflakes $rootdir/virt-subproc/adt-virt-$v
done
