#!/bin/sh
# Run tests for different runners in parallel

MYDIR=$(dirname $0)

# these are fast, run them first
set -e
$MYDIR/pep8
$MYDIR/pyflakes
set +e

# parse out the AdtTestCase classes
CLASSES=`grep -oP '(?<=class )[a-zA-Z]+(?=\(AdtTest)' tests/adt-run`

for c in $CLASSES; do
    (OUT=$($MYDIR/adt-run $c 2>&1) || rc=$?; echo "=== $c ==="; echo "$OUT"; exit $rc) &
done
for c in $CLASSES; do wait; done
